require_relative '../rental'
require_relative '../classroom'
require_relative '../teacher'
require_relative '../student'
require_relative '../book'
require_relative '../trimmer_decorator'
require 'date'
require 'rspec'
